apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    {{- include "reviews.labels" . | nindent 4}}
    app.kubernetes.io/component: reviews
spec:
  replicas: {{ .Values.reviews.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name : reviews
      app.kubernetes.io/instance: {{ .Release.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name : reviews
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: reviews
          image: {{ .Values.reviews.image }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000